---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: confluent-oss
  namespace: confluent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: confluent-oss
  chart:
    repository: https://confluentinc.github.io/cp-helm-charts/
    name: cp-helm-charts
    version: 0.6.0
  values:
    ## ------------------------------------------------------
    ## Zookeeper
    ## ------------------------------------------------------
    cp-zookeeper:
      servers: 5
    ## ------------------------------------------------------
    ## Kafka Connect
    ## ------------------------------------------------------
    cp-kafka-connect:
      enabled: false