---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 11.1.5
  values:
    alertmanager.enabled: true
    kubeStateMetrics.enabled: true
    nodeExporter.enabled: true
    podSecurityPolicy.enabled: false #to confirm
    rbac.create: true
    server.enabled: true
    server.name: prometheus-server
    server.ingress.enabled: true
    